### ISSUE TITLE
Watchdog automatically assumes the bot isn't down when adding it to the database

### ISSUE THREAD

**Issue by ellieisjelly** [HyacinthBots/Lily-watchdog#3]
As seen in line 99 of the WatchedBot extension, the code doesn't check if the bot was offline when it's added to the database

**Comment by NoComment1105** [comment]
This is unimportant. if the bot is offline when added, it will still be flagged when the check runs. It's no different to it going down in the few minutes after addition. Even if it is offline it will have incorrect timing too
